#!/usr/bin/python
import sys
import subprocess

try:
  if(sys.argv[-2] == "-o"):
    subprocess.call('verilator '+' '.join(sys.argv[1:-2])+"> "+sys.argv[-1],shell=True)
  else:
    subprocess.call('verilator '+' '.join(sys.argv[1:]),shell=True)
except:
  subprocess.call('verilator '+' '.join(sys.argv[1:]),shell=True)
print(sys.argv)
