#!/usr/bin/python
import sys
import subprocess

try:
  posO = sys.argv.index('-o')
  print(posO)
  toCall = 'verilator '+' '.join(sys.argv[1:posO]) + ' ' + ' '.join(sys.argv[posO+2:]) +" > "+sys.argv[posO+1]
  print(toCall)
  subprocess.call(toCall,shell=True)
except:
  print(sys.argv)
  subprocess.call('verilator '+' '.join(sys.argv[1:]),shell=True)
print(sys.argv)
